language: node_js

node_js:
  - 7.4.0

branches:
  only:
    - master

before_deploy:
  - terraform_url=$(curl https://releases.hashicorp.com/index.json | jq '{terraform}' | egrep "linux.*amd64" | sort --version-sort -r | head -1 | awk -F[\"] '{print $4}')
  - curl -o terraform.zip $terraform_url
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

deploy:
  provider: script
  script: make deploy
  on:
    branch: master

env:
  global:
    - secure: dIfGiV9iwCwMXr4fA47jKl1+Az6yyP2i2py152VR4HDPpj1vRyWFUEGP8d4fLdt0FLKa9Gn3iy2AuBb6Tb3xZ7RXqkn+9xVMcgeMCTGqQ59P9h6dFWGWd2CslkNcHXgRkFHeNFedDdkkw0CFWHbc/m5jBQ6QcPwjQa8hkEITkiznyPGrQ5RBq1C89A6RM5qDrAdvSEoq90C+VXpF4P0mVoIyBk4hxctr9taXP8erTs2bdwhvYivTEt0KxPwsF7DzZX5lIXn4B/bynN6ckLPyvlSSh4ZLKzqLKep8P7DJr80xOrZfFTouxow8/X7zh7fW5typdnDw7mUwDFJC8/EbjvMH4ElITjpoUvk7TBp+9SAz1y7N94FD/YavAQQlpK7xDFnoQLGfAnmNa++zTzg8jvawjciVTl7b2zGuLrtCHuDyHnPTid08+kU8djr7s7c6od9J9KqnCDBWQj7eUgDKZXu3ARE7r4ZxWMUn9zvwlCsAjcpQJNSfn1dpq43nedKa8D7eZ2ffG9nC4h0j3CjHEVbJFC7jR7S3umX5P4SVsFXQfHL9LpkiL5telqHhnYU2Zxbdgm1O8TwI1Sh2W0LGKne/XH+HVLmMSbZEzApIGUcmebB44gAcYKQ22ZyrLCBUsCsquHv5kblmSa2gCyTiRfV9E+G+gtpXPSFBvY8QhoA=
    - secure: BlqDexVwnUtiRxNuI0QB4NusT+rhPpmoPrLm71yghZIn8rZ3MtFR01RIcvUZgG2eHgYH/KHhgM+aLNVASG2tSHsjAeFUoN492b8GRNJ1WuTSGiJOT1kpv3Y2nuQVqZd9YSBQD9icidPd4eFVHXj9onURRWQ3+Wet4CEQnMkUHXWiNTlhAxIm7bqZxX+Bl3ahRp4m2BTjdpCfF8XC086/oDcUmgBoFW0UyChyHIfalWRNNLeVDAlvwpsbu9w/+sJ8gSfokkRof+ATl6Z67n7svUFTrul9/YkPLUFd4652wonQ7cK+amz0z2dTYLwvG/sFLYkFa0sWw3ICWiHZKkW1dQVo98UsxBu8lbO78H3FTxM46lrk3PEoY+EnqhjOhwbfzsPNtCUDPf2HJKLoJa1WqWHLtFVIxOHqnutC4umwdgqvqHFKZtXEXRBK6GBc/sxiKzeL48BZkiEp5IFT0e/o7oZMI77F2Uw0NNTZmwSc+RnSQACQT+HBW/TVrJiteE7ABkiePWBqFrzVcLu6WzMYH0iWhqSspo2ssl+JjGItrkVIPRtDFwKiPwQySs74eumY9RQjy9dQtzaBKGPcQvl7yBIGvA5AKF/PVRqqKL0wFGJLLbLqfh2VU2f2AHeE6lMper0psRux3wAFGf3ckXjowZKJVdMybKh6C4evhzAt1o0=