language: node_js
node_js:
- 7.4.0
branches:
  only:
  - master
before_deploy:
- terraform_url=$(curl https://releases.hashicorp.com/index.json | jq '{terraform}'
  | egrep "linux.*amd64" | sort --version-sort -r | head -1 | awk -F[\"] '{print $4}')
- curl -o terraform.zip $terraform_url
- sudo unzip terraform.zip -d /opt/terraform
- sudo ln -s /opt/terraform/terraform /usr/bin/terraform
- rm -f terraform.zip
deploy:
  provider: script
  script: make deploy
  on:
    branch: master
env:
  global:
    - secure: beEC+2Hnec87ntzEk2GzFoV5m5UcPX/xoL0JEE8XlhTjGaTABlLp1pkyGQyGxDt7VzaHuFWK+zqzWIloHXR3lmcI+eqD4G6Xd2o7xSiChFDy8wQeBV69LjSQ+NKOqcCH1M7V2tHILDr4aRQUz4pBYOGblBE0IiaeYjAUbQi7FAqZRMOVuarfF1T/YLEq39wCz0FbXaukAqGeOhmNxL3asphtHm0VGIy3Tns4xRIqzEnwe1KMz9mzVx8dYM/88/b21icNs9dH9hMQL+HWCS3XQ/uvhxEon+EHl+D9gi0cVQeBDq/awIeKuxT+Mju3eM7jxmGf4nKUB1y2XXnXXJ3fH6NlBe3yRqNkiPi7fQdiYzo3mBI/m2pXnE+2d0/Bv4MJHDwLQi8DYIef2bnrUiMBSxH/SpjUaG0qKiHiCtHQOiMn1ipl+dQS8+bTUkj0+Y7Ns6f7/anZ6eDTwiIqnYKkhYInvYkPfehCtXoKvSJcnn9hf4AW+EX24dehv4nE5LZORQ6KY9oeIzV3DCUa9z+XWvQe/dCb5wTElvNKkWzTwh7tGrBKDG4xLb72GYVtciTTyStoyMVOg8VRnReAeJDwGm79tzWk05/8FoTWinvTbVTHN4lyNqz6BE+By+dtAn/bLTEA1jPNvH7QcWi393OaUA9j/+c+BZ0bpI6v7h+ybng=
    - secure: d8CKXjoSZ7CDN+rMZVRcU76L0PH2CqNL3F60DiX5b8HQxWqMWdEjZebp5MhiXz1ntK/9w6UvEzK4kUwo5uc4tTMqzdKVCrvHQFDVLUROucILnBTtoW29/1u6/6v8leMWh7wed4S7OaHnii5FTGJIbnJTizNFzh6w0W/VQetH5ed06+tMi6idN8K2Ba4hPD4hJa9CGApBBNPF4gBXd0Lw7/1HuAtrQoPqPa/FBeTSuSpIXSbjNeLSiRHh4NDrNRZkS7vyA22zAlBoONQRo1yAs5xqTW8rMM9yhqm+yiaK6fyZRCkaB4oNaX/IX153H6jlnL+S6rE/XcdqURZb6hUpt3y8IoDWiAsqD3T4LwpuNkPRgBQl307BQhG8i9JwmKEe16gbvH2GdMPxUvDzhh2B437xwstnJRHFYOQ4cI8/HRLCuEgLELxhGW83Z8mOTQ+xINiSCsmEXzze3ywijG4N8/PNZak++7nD7yqxKQLBvzqu72TY34FHaRA7t3Nr1OZwa9ADyzwdWHXM8ODr6Id5yqBoAYxwxB0fK/pz8eGH1LVCzsxPghVFv35hbTgjhZ3fdIArbWReSYHSc0xzGDEG/9Khj+6tEFnrIfvGwY4r+xHo57Zbfr4f55EBfW0pVunbQQTWuK6+GXxMM/gOaLdRd184wW6xnXjX7tYV5rAGmTQ=
