language: node_js
node_js:
- 7.4.0
branches:
  only:
  - master
before_deploy:
- terraform_url=$(curl https://releases.hashicorp.com/index.json | jq '{terraform}'
  | egrep "linux.*amd64" | sort --version-sort -r | head -1 | awk -F[\"] '{print $4}')
- curl -o terraform.zip $terraform_url
- sudo unzip terraform.zip -d /opt/terraform
- sudo ln -s /opt/terraform/terraform /usr/bin/terraform
- rm -f terraform.zip
deploy:
  provider: script
  script: make deploy
  on:
    branch: master
env:
  matrix:
  - secure: dZ3Xix++ucF6hteDr8z45BMo0cKgRrzNhKR8ZXOXTMi7/VSUlbWUVdemog93oVv6cQkyOdMzac8KdzJ/FgiJKBubhjc6ijUy9fRD+Nq8AysH8jPTbofHfrXR2YWXdU3+uONaOxlMEHoTTyovaFQoVSB1SusycWp9Hp2ZItbrejDcaJahfrnY87iTGUV7MYmOXbwUKiX5FexvuZ2adbbtWYQ2tkD8FqwYAezo5DHoIqaA5dFyjaJ5XCrId1SZb6TTJw49QJ47XDwi1U1lnXMxN30xtnxb92d4dieR6Af2GKovjSnhBP5UZlqsfpV1vnQ5hqaZD8q5oJJkx3UfRzGFS5m3hRS99nwaIIzrJp3x5DE3EemTS/yyHdoiZ4/lsFhB+n4dQhwCvtdYHHCbKf0PUShpb44vbdnmmyxeX1sYyCnE0WQFNLWJ9UsuE7oDKDX1xmDrZc+LMUKync7I7yq6O2+ZHOvowOYz4KfcjiGGdKLVQ6QF49T5XZFWrCzzwBpFkjIgP4ZMWeRn34mGGysFiBExQX9UvwFHft61YEhtBAugvTl0F3z86ux13VsEYlQPZ22vp50gZtZahoa7KSgSP0gAO6zHbRRP35bD84/OpyMFswL3Pq/qVvTHVLX/KnvITGBhK8yX1CsluG1O+R9fR4JtmAg3mKMCbEbhFc2PzBs=
  - secure: Pdf+Or9LaBtoGJF60xwafEQa8na+jeDPNJRvJFMn0xWE51/rY5zk79qoe1lhKZYl+F54hucWmrr96jli7ACAGCGyIK7Xqv0T/qshmdXUYrLwNJtNgmMR9biL6xOkPbQNVnc9qitj4i279ArcjqOP8EeRAp5HZMavVFDABsWZ1lWmpb66mg3tvR8rEjofOZkspGOISXdRu7kwwl9GOjLOhR4r9Z/Pnnofl1MaMd/r+jbYTFjhsIbHb4/wiRWxhPVO5UM4CZ+Fyc0nShX/lCgRcPsDHVV9wII+OQERMwvGYd3z9t2QWVSZXjVL5MLlOfmOTkm6WgG96NXHDe+iN6cAgvk4vmH1vtJsp2ZOq6aeb8VdHMJ41mzZSxhKB6NXAWIyVBdjlHwFX/IZZZ2opR2UvqmfqdEnIUDQLOapJqg8BdWHQj6K3SqcLQAoUG94ex1hx9pkyI9MRQlpDLjMgXqZj09vec5S2wOpZyeJW2hkc2czSFlxBUesIwJKk2p4mZsnHgnv8gPBfUjd+vV6CNvJAL2l7sQjRsY9FI8Tk7mYxkmLGOIVU8y87yPv9P5qq3VuQBBBDPkk/N2eFuH7ABMS4ukJ3R5aYJAYHEXr9KIOrr7h4pqEkDulk6GYcx1oxKYQnSFBWpMa7cjsYIy0ikh7L0YY7KwGoZM2R4kuQz+z8Ng=
  - secure: jicf5ei8l88MRdbkb6JcnzcvIRncHLCAUdUaJWMK0xPpO6+w1Rn92DEnqe0xdUQeQcGzw4/r8i7aL5UdUMHz45oV1Mfl2N8oraKfAesfVTERjul5LrdQ5u82f2sPxmDkA2ye8rWFqLOE0H/YCWEHEg5FS6GBLQwhWvFGRdM4IqOb3P3Co7Sgo1phzUP24ksPOKuewM42JzHg9QC5nACmMKLpZJ2NB4XowUfnc10pzRqUK7CcTh+Jgi6Gec1J3EREOqNq3z6dYQDL+somSCO3IaV0zJhB5/Fa3UZJuPPGWwivLr15wRfbfYgvW7Y0Gsw6gMUZTuvWEnIKmUfmyXnv565KZVsk900CbUCsY8d+u/K/sNrmOIb5i3xflC5BO/nIC0tuv6NXxx1DrW9AggsfwPGUSf0LZdh3WdJ8phaENsudsWE3z8NEoIe+vDYjqifLYqkPnXKeFnE8m5Tiq3n1L/1R5GTjoONHk+6ljhZ1aDCbWcOHHrdUuXdVwOfrExQ7W2yQ5JLX/Yn144nMSq6/zrNlnJW1FukwQTfPkGoFZbNCN8Atv8ATrsPwSEBdfd5aZaxDuQnD9IR2YfxGsr8ViBZpmvplTfH1Jc3efXTBJ29JTiM9d/OhVYQKpsWSkmzM2/023zAyNovGIEb2T3hpOE6JWHJMCEJfjv+He3rbeXs=
