language: node_js

node_js:
  - 7.4.0

branches:
  only:
    - master

before_deploy:
  - terraform_url=$(curl https://releases.hashicorp.com/index.json | jq '{terraform}' | egrep "linux.*amd64" | sort --version-sort -r | head -1 | awk -F[\"] '{print $4}')
  - curl -o terraform.zip $terraform_url
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

deploy:
  provider: script
  script: make deploy
  on:
    branch: master

env:
  global:
    - secure: Nzm7Wrnyqu/9sQ+9PHoTRVjXFaM0eMFIozaEV66zbDuN6Msq67ata2Pzq019lIFmzcMDslvy87QBex+xUHPIkOmv4EwPXX65nbIrdOi2+vO3ai3HQVEVpeXjkc86JK6xG3wJ08dxuTs5+gFuJNcRUY9Pdy7kMCI5xG4IOVnxnhaxi0NajPl9vmQ2W+LdvlKQfmAiS6g+JYgD3q/WZmhzglWvh9wmKWcjLemNsWoxrdKR3q9JUW0ngNzwwnyzVxghYpzTSWhEswrlBFqCzRfcHVxeB6WD0IfDoDsmIUhy24yA22iNhC2y5IdiP0oz6HdAvIar3VtADafrm6PJ8eFuA1tKc6lgqXA9z0+j4i9e1dZtpb+WTD0EWkgDY17Q99j8w13orDG4mGLZpX8XinLii+rMvZ55YxoYp5UjaCGKniAK+xKFmZwHnEU+RdyMcE6Jf4pqd1R3eKJ3HWlT5Qg1gKy40sTTS7PbgmUDXu/h8tSkLk1oGd5g0kq2YQApReB5OZYtsNJixQHeUxBW2FHyUIjSTnbWgG/eBzjZS4Aw0BEeORsbc6q56Jb1ybK3nBPDqe9g5fVOWL9W6eTgJnoEDj2+O7s/6qB9t1hkVeu4PywctCoHUT2eieWrHVQgHK1dYBAYw3l9eeH4RlhVDA87l5XA6LpPqtkzveFsDGlYfS4=
    - secure: H4b+X6bZPQYfVIQvF3yHyApY1Szi3IdTFV5/shmZ5p6zAqyhWT3drr+XiGM3ELW6kC+0ovYedEXvFzzzSTNrrlWBbrtmI0Hj7GjUYfXizo8dM4XalG3R9oVsuKiFdwZyffyjVXb14Bvyt/eG5VgSFxV8RM+jLGFTFkFSvXku8LcAxBYs5LCloEHnrvLe3a+gsejNDlrmXkg0fc8VgPPJ1nqwP3j18qbfL8XTlqLVrOc+sGVy8S+pRj/pMQNMvqJ0aNC7xRop0vG5vd4XirEnmdv3rUGSbLuoQ8p0Zpv9WC6geCl7o2IlZpaooFN2woqdqS4sp/nFpkPCx0uplUBW8H0iJzfl6kA5VWLgBHFrDxDddSZNdbK+5R7J51HPR+m25rlhyF2AJkMI70URnPeBqghe1dP4oxopphlfkprftpoyw69EmOfp5gXa/7q9e5jd35N2rjy2fukaYWd8wLJd/q2FrsGtKHAIdyryWx4ztA02niOh3sY89HM0e24/8jb0+G2VvRJkKBWNpDC62BbWjOGXltAUzDfTAV8XSk7AVkzqkMFbXK8z9sSGmeEuLHTyFJsPW3YI5MhYJ9zwoiGjg4wsTLdnSG+KQRoXI+AsWRoekE8X5JR0kvepT4iYLOJC/iecCEUYx1rnajyiCPoVuNZ39qzy1kLGSy5sUmTx0U4=
